###############################
# BUILD FOR LOCAL DEVELOPMENT #
###############################

FROM node:18.16.0-alpine as dev

ENV NODE_ENV=dev

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . .


###############################
#### BUILD FOR PRODUCTION #####
###############################

FROM node:18.16.0-alpine As build

ENV NODE_ENV=production

WORKDIR /app

COPY --chown=node:node package*.json ./
COPY --chown=node:node --from=dev /app/node_modules ./node_modules
COPY --chown=node:node . .

RUN npm run build

USER node

##############################
######### PRODUCTION #########
##############################

FROM nginx:latest as production

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
